services:
  dash-prod:
    build: .
    environment:
      - BIND_IP=0.0.0.0
    ports:
      - "8080:8000"
      - "80:8000"
  dash-dev:
    build:
      context: .
      target: dev
    profiles: ["dev"]
    ports:
      - "8070:8070"


