services:
  dash-prod:
    build: .
    environment:
      - BIND_IP=0.0.0.0
      - fetch=True
    ports:
      - "8080:8000"
      - "80:8000"
  dash-dev:
    build:
      context: .
      target: dev
    environment:
      - fetch=false
    profiles: ["dev"]
    ports:
      - "8070:8070"


